CREATE SCHEMA IF NOT EXISTS pr;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS pr.users (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    chat_id BIGINT NOT NULL UNIQUE
);
